#Dockerfile
FROM node:19.6.1-alpine3.17 as builder

ARG REACT_APP_WANTED_ENDPOINT
ARG REACT_APP_WANTED_ID
ARG REACT_APP_WANTED_SECRET

WORKDIR /app
COPY . /app


RUN echo "REACT_APP_WANTED_ENDPOINT=${REACT_APP_WANTED_ENDPOINT}" >> .env
RUN echo "REACT_APP_WANTED_ID=${REACT_APP_WANTED_ID}" >> .env
RUN echo "REACT_APP_WANTED_SECRET=${REACT_APP_WANTED_SECRET}" >> .env

RUN npm install
RUN npm run build

RUN rm .env

FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]