#Dockerfile
FROM node:19.6.1-alpine3.17 as builder

ARG REACT_APP_WANTED_ENDPOINT
ARG REACT_APP_WANTED_ID
ARG REACT_APP_WANTED_SECRET

WORKDIR /app
COPY . /app

RUN npm install --legacy-peer-deps
RUN npm run build 

FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]